export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN_BKPSDM = 'ADMIN_BKPSDM',
  OPERATOR_OPD = 'OPERATOR_OPD',
  PELAKSANA = 'PELAKSANA',
  ANALIS_PERTAMA = 'ANALIS_PERTAMA',
  ANALIS_MUDA = 'ANALIS_MUDA',
  ANALIS_MADYA = 'ANALIS_MADYA',
  KEPALA_BIDANG = 'KEPALA_BIDANG',
  KEPALA_BADAN = 'KEPALA_BADAN',
  PPPK_PARUH = 'PPPK_PARUH',
}
