export const INTEGRASI_IMPORT_STATUS = {
  DRAFT: 'DRAFT',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  VALIDATED_WITH_ERROR: 'VALIDATED_WITH_ERROR',
  COMMITTING: 'COMMITTING',
  IMPORTED: 'IMPORTED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type IntegrasiImportStatus =
  (typeof INTEGRASI_IMPORT_STATUS)[keyof typeof INTEGRASI_IMPORT_STATUS];

export const INTEGRASI_IMPORT_STATUS_VALUES = Object.values(
  INTEGRASI_IMPORT_STATUS,
);

export const VALIDATE_ALLOWED_STATUSES: readonly IntegrasiImportStatus[] = [
  INTEGRASI_IMPORT_STATUS.DRAFT,
  INTEGRASI_IMPORT_STATUS.VALIDATED_WITH_ERROR,
  INTEGRASI_IMPORT_STATUS.FAILED,
];

export const COMMIT_ALLOWED_STATUSES: readonly IntegrasiImportStatus[] = [
  INTEGRASI_IMPORT_STATUS.VALIDATED,
];

export const CANCEL_ALLOWED_STATUSES: readonly IntegrasiImportStatus[] = [
  INTEGRASI_IMPORT_STATUS.DRAFT,
  INTEGRASI_IMPORT_STATUS.VALIDATED,
  INTEGRASI_IMPORT_STATUS.VALIDATED_WITH_ERROR,
  INTEGRASI_IMPORT_STATUS.FAILED,
];

export const INTEGRASI_IMPORT_EVENT = {
  VALIDATE_STARTED: 'IMPORT_VALIDATE_STARTED',
  VALIDATE_SUCCESS: 'IMPORT_VALIDATE_SUCCESS',
  VALIDATE_FAILED: 'IMPORT_VALIDATE_FAILED',
  COMMIT_STARTED: 'IMPORT_COMMIT_STARTED',
  COMMIT_SUCCESS: 'IMPORT_COMMIT_SUCCESS',
  COMMIT_FAILED: 'IMPORT_COMMIT_FAILED',
  CANCELLED: 'IMPORT_BATCH_CANCELLED',
  REFERENCE_CREATE_SUCCESS: 'IMPORT_REFERENCE_CREATE_SUCCESS',
} as const;