-- AlterTable: extend LayananStatus enum with new multi-level workflow states
ALTER TABLE `silakap_layanan_log`
  MODIFY COLUMN `status` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL;

ALTER TABLE `silakap_usul_layanan`
  MODIFY COLUMN `status` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL DEFAULT 'DRAFT';

ALTER TABLE `silakap_workflow_dependency`
  MODIFY COLUMN `trigger_status` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL,
  MODIFY COLUMN `blocking_status` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL;

ALTER TABLE `silakap_workflow_sla`
  MODIFY COLUMN `state` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL;

ALTER TABLE `silakap_workflow_sla_instance`
  MODIFY COLUMN `state` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL;

ALTER TABLE `silakap_workflow_timeline`
  MODIFY COLUMN `fromStatus` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL,
  MODIFY COLUMN `toStatus` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL;

ALTER TABLE `silakap_workflow_transition`
  MODIFY COLUMN `fromState` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL,
  MODIFY COLUMN `toState` ENUM('DRAFT','SUBMITTED','CHECKED','VERIFIED','REVIEWED','RECOMMENDED','RETURNED','APPROVED','REJECTED','COMPLETED','SYNCED_SIASN','FAILED_SIASN') NOT NULL;
