export type WorkflowState =
  | "DRAFT"
  | "SUBMITTED"
  | "IN_REVIEW"
  | "VERIFIED"
  | "RETURNED"
  | "APPROVED"
  | "REJECTED"
  | "SYNCED_SIASN"
  | "FAILED_SIASN"
  | "COMPLETED"

export type WorkflowAction =
  | "SUBMIT"
  | "VERIFY"
  | "RETURN"
  | "APPROVE"
  | "REJECT"
  | "SYNC_SIASN"
  | "RETRY_SIASN"
