//D:\_silakap_web\src\core\rbac\permissions.ts
export const PERMISSIONS = {
  // SYSTEM
  SYSTEM_CONFIG_READ: "SYSTEM.CONFIG.READ",
  SYSTEM_CONFIG_UPDATE: "SYSTEM.CONFIG.UPDATE",
  SYSTEM_HEALTH_CHECK: "SYSTEM.HEALTH.CHECK",

  // SECURITY - USER
  SECURITY_USER_READ: "SECURITY.USER.READ",
  SECURITY_USER_CREATE: "SECURITY.USER.CREATE",
  SECURITY_USER_UPDATE: "SECURITY.USER.UPDATE",
  SECURITY_USER_DELETE: "SECURITY.USER.DELETE",

  // SECURITY - ROLE
  SECURITY_ROLE_READ: "SECURITY.ROLE.READ",
  SECURITY_ROLE_CREATE: "SECURITY.ROLE.CREATE",
  SECURITY_ROLE_UPDATE: "SECURITY.ROLE.UPDATE",
  SECURITY_ROLE_DELETE: "SECURITY.ROLE.DELETE",

  // SECURITY - PERMISSION
  SECURITY_PERMISSION_READ: "SECURITY.PERMISSION.READ",
  SECURITY_PERMISSION_UPDATE: "SECURITY.PERMISSION.UPDATE",

  // SECURITY - AUDIT
  SECURITY_AUDIT_READ: "SECURITY.AUDIT.READ",
  SECURITY_AUDIT_EXPORT: "SECURITY.AUDIT.EXPORT",

  // ASN
  ASN_READ: "ASN.READ",
  ASN_CREATE: "ASN.CREATE",
  ASN_UPDATE: "ASN.UPDATE",
  ASN_DELETE: "ASN.DELETE",
  ASN_IMPORT_SIASN: "ASN.IMPORT.SIASN",

  // SERVICE
  SERVICE_CREATE: "SERVICE.CREATE",
  SERVICE_SUBMIT: "SERVICE.SUBMIT",
  SERVICE_VERIFY: "SERVICE.VERIFY",
  SERVICE_RETURN: "SERVICE.RETURN",
  SERVICE_APPROVE: "SERVICE.APPROVE",
  SERVICE_REJECT: "SERVICE.REJECT",
  SERVICE_VIEW_ALL: "SERVICE.VIEW.ALL",
  SERVICE_VIEW_OPD: "SERVICE.VIEW.OPD",
  SERVICE_VIEW_SELF: "SERVICE.VIEW.SELF",

  // DOCUMENT
  DOC_READ: "DOC.READ",
  DOC_UPLOAD: "DOC.UPLOAD",
  DOC_DELETE: "DOC.DELETE",
  DOC_SIGN_TTE: "DOC.SIGN.TTE",

  // SIASN
  SIASN_SYNC_TRIGGER: "SIASN.SYNC.TRIGGER",
  SIASN_SYNC_RETRY: "SIASN.SYNC.RETRY",
  SIASN_SYNC_VIEW: "SIASN.SYNC.VIEW",

  /* ================= MASTER ================= */

  // AGAMA
  MASTER_AGAMA_VIEW: "MASTER.AGAMA.VIEW",
  MASTER_AGAMA_CREATE: "MASTER.AGAMA.CREATE",
  MASTER_AGAMA_UPDATE: "MASTER.AGAMA.UPDATE",
  MASTER_AGAMA_DELETE: "MASTER.AGAMA.DELETE",
  MASTER_AGAMA_RESTORE: "MASTER.AGAMA.RESTORE",

  // ALASAN PENSIUN
  MASTER_ALASAN_PENSIUN_VIEW: "MASTER.ALASAN_PENSIUN.VIEW",
  MASTER_ALASAN_PENSIUN_CREATE: "MASTER.ALASAN_PENSIUN.CREATE",
  MASTER_ALASAN_PENSIUN_UPDATE: "MASTER.ALASAN_PENSIUN.UPDATE",
  MASTER_ALASAN_PENSIUN_DELETE: "MASTER.ALASAN_PENSIUN.DELETE",
  MASTER_ALASAN_PENSIUN_RESTORE: "MASTER.ALASAN_PENSIUN.RESTORE",

  // GOLONGAN
  MASTER_GOLONGAN_VIEW: "MASTER.GOLONGAN.VIEW",
  MASTER_GOLONGAN_CREATE: "MASTER.GOLONGAN.CREATE",
  MASTER_GOLONGAN_UPDATE: "MASTER.GOLONGAN.UPDATE",
  MASTER_GOLONGAN_DELETE: "MASTER.GOLONGAN.DELETE",
  MASTER_GOLONGAN_RESTORE: "MASTER.GOLONGAN.RESTORE",

  // INSTANSI
  MASTER_INSTANSI_VIEW: "MASTER.INSTANSI.VIEW",
  MASTER_INSTANSI_CREATE: "MASTER.INSTANSI.CREATE",
  MASTER_INSTANSI_UPDATE: "MASTER.INSTANSI.UPDATE",
  MASTER_INSTANSI_DELETE: "MASTER.INSTANSI.DELETE",
  MASTER_INSTANSI_RESTORE: "MASTER.INSTANSI.RESTORE",

  // JABATAN
  MASTER_JABATAN_VIEW: "MASTER.JABATAN.VIEW",
  MASTER_JABATAN_CREATE: "MASTER.JABATAN.CREATE",
  MASTER_JABATAN_UPDATE: "MASTER.JABATAN.UPDATE",
  MASTER_JABATAN_DELETE: "MASTER.JABATAN.DELETE",
  MASTER_JABATAN_RESTORE: "MASTER.JABATAN.RESTORE",

  // JENIS JABATAN
  MASTER_JENIS_JABATAN_VIEW: "MASTER.JENIS_JABATAN.VIEW",
  MASTER_JENIS_JABATAN_CREATE: "MASTER.JENIS_JABATAN.CREATE",
  MASTER_JENIS_JABATAN_UPDATE: "MASTER.JENIS_JABATAN.UPDATE",
  MASTER_JENIS_JABATAN_DELETE: "MASTER.JENIS_JABATAN.DELETE",
  MASTER_JENIS_JABATAN_RESTORE: "MASTER.JENIS_JABATAN.RESTORE",

  // JENIS KELAMIN
  MASTER_JENIS_KELAMIN_VIEW: "MASTER.JENIS_KELAMIN.VIEW",
  MASTER_JENIS_KELAMIN_CREATE: "MASTER.JENIS_KELAMIN.CREATE",
  MASTER_JENIS_KELAMIN_UPDATE: "MASTER.JENIS_KELAMIN.UPDATE",
  MASTER_JENIS_KELAMIN_DELETE: "MASTER.JENIS_KELAMIN.DELETE",
  MASTER_JENIS_KELAMIN_RESTORE: "MASTER.JENIS_KELAMIN.RESTORE",

  // JENIS LAYANAN
  MASTER_JENIS_LAYANAN_VIEW: "MASTER.JENIS_LAYANAN.VIEW",
  MASTER_JENIS_LAYANAN_CREATE: "MASTER.JENIS_LAYANAN.CREATE",
  MASTER_JENIS_LAYANAN_UPDATE: "MASTER.JENIS_LAYANAN.UPDATE",
  MASTER_JENIS_LAYANAN_DELETE: "MASTER.JENIS_LAYANAN.DELETE",
  MASTER_JENIS_LAYANAN_RESTORE: "MASTER.JENIS_LAYANAN.RESTORE",

  // JENIS PEGAWAI
  MASTER_JENIS_PEGAWAI_VIEW: "MASTER.JENIS_PEGAWAI.VIEW",
  MASTER_JENIS_PEGAWAI_CREATE: "MASTER.JENIS_PEGAWAI.CREATE",
  MASTER_JENIS_PEGAWAI_UPDATE: "MASTER.JENIS_PEGAWAI.UPDATE",
  MASTER_JENIS_PEGAWAI_DELETE: "MASTER.JENIS_PEGAWAI.DELETE",
  MASTER_JENIS_PEGAWAI_RESTORE: "MASTER.JENIS_PEGAWAI.RESTORE",

  // JENIS PENSIUN
  MASTER_JENIS_PENSIUN_VIEW: "MASTER.JENIS_PENSIUN.VIEW",
  MASTER_JENIS_PENSIUN_CREATE: "MASTER.JENIS_PENSIUN.CREATE",
  MASTER_JENIS_PENSIUN_UPDATE: "MASTER.JENIS_PENSIUN.UPDATE",
  MASTER_JENIS_PENSIUN_DELETE: "MASTER.JENIS_PENSIUN.DELETE",
  MASTER_JENIS_PENSIUN_RESTORE: "MASTER.JENIS_PENSIUN.RESTORE",

  // KEDUDUKAN HUKUM
  MASTER_KEDUDUKAN_HUKUM_VIEW: "MASTER.KEDUDUKAN_HUKUM.VIEW",
  MASTER_KEDUDUKAN_HUKUM_CREATE: "MASTER.KEDUDUKAN_HUKUM.CREATE",
  MASTER_KEDUDUKAN_HUKUM_UPDATE: "MASTER.KEDUDUKAN_HUKUM.UPDATE",
  MASTER_KEDUDUKAN_HUKUM_DELETE: "MASTER.KEDUDUKAN_HUKUM.DELETE",
  MASTER_KEDUDUKAN_HUKUM_RESTORE: "MASTER.KEDUDUKAN_HUKUM.RESTORE",

  // KPKN
  MASTER_KPKN_VIEW: "MASTER.KPKN.VIEW",
  MASTER_KPKN_CREATE: "MASTER.KPKN.CREATE",
  MASTER_KPKN_UPDATE: "MASTER.KPKN.UPDATE",
  MASTER_KPKN_DELETE: "MASTER.KPKN.DELETE",
  MASTER_KPKN_RESTORE: "MASTER.KPKN.RESTORE",

  // LOKASI KERJA
  MASTER_LOKASI_KERJA_VIEW: "MASTER.LOKASI_KERJA.VIEW",
  MASTER_LOKASI_KERJA_CREATE: "MASTER.LOKASI_KERJA.CREATE",
  MASTER_LOKASI_KERJA_UPDATE: "MASTER.LOKASI_KERJA.UPDATE",
  MASTER_LOKASI_KERJA_DELETE: "MASTER.LOKASI_KERJA.DELETE",
  MASTER_LOKASI_KERJA_RESTORE: "MASTER.LOKASI_KERJA.RESTORE",

  // PENDIDIKAN
  MASTER_PENDIDIKAN_VIEW: "MASTER.PENDIDIKAN.VIEW",
  MASTER_PENDIDIKAN_CREATE: "MASTER.PENDIDIKAN.CREATE",
  MASTER_PENDIDIKAN_UPDATE: "MASTER.PENDIDIKAN.UPDATE",
  MASTER_PENDIDIKAN_DELETE: "MASTER.PENDIDIKAN.DELETE",
  MASTER_PENDIDIKAN_RESTORE: "MASTER.PENDIDIKAN.RESTORE",

  // PENDIDIKAN TINGKAT
  MASTER_PENDIDIKAN_TINGKAT_VIEW: "MASTER.PENDIDIKAN_TINGKAT.VIEW",
  MASTER_PENDIDIKAN_TINGKAT_CREATE: "MASTER.PENDIDIKAN_TINGKAT.CREATE",
  MASTER_PENDIDIKAN_TINGKAT_UPDATE: "MASTER.PENDIDIKAN_TINGKAT.UPDATE",
  MASTER_PENDIDIKAN_TINGKAT_DELETE: "MASTER.PENDIDIKAN_TINGKAT.DELETE",
  MASTER_PENDIDIKAN_TINGKAT_RESTORE: "MASTER.PENDIDIKAN_TINGKAT.RESTORE",

  // SATKER
  MASTER_SATKER_VIEW: "MASTER.SATKER.VIEW",
  MASTER_SATKER_CREATE: "MASTER.SATKER.CREATE",
  MASTER_SATKER_UPDATE: "MASTER.SATKER.UPDATE",
  MASTER_SATKER_DELETE: "MASTER.SATKER.DELETE",
  MASTER_SATKER_RESTORE: "MASTER.SATKER.RESTORE",

  // STATUS KEPEGAWAIAN
  MASTER_STATUS_KEPEGAWAIAN_VIEW: "MASTER.STATUS_KEPEGAWAIAN.VIEW",
  MASTER_STATUS_KEPEGAWAIAN_CREATE: "MASTER.STATUS_KEPEGAWAIAN.CREATE",
  MASTER_STATUS_KEPEGAWAIAN_UPDATE: "MASTER.STATUS_KEPEGAWAIAN.UPDATE",
  MASTER_STATUS_KEPEGAWAIAN_DELETE: "MASTER.STATUS_KEPEGAWAIAN.DELETE",
  MASTER_STATUS_KEPEGAWAIAN_RESTORE: "MASTER.STATUS_KEPEGAWAIAN.RESTORE",

  // STATUS PERKAWINAN
  MASTER_STATUS_PERKAWINAN_VIEW: "MASTER.STATUS_PERKAWINAN.VIEW",
  MASTER_STATUS_PERKAWINAN_CREATE: "MASTER.STATUS_PERKAWINAN.CREATE",
  MASTER_STATUS_PERKAWINAN_UPDATE: "MASTER.STATUS_PERKAWINAN.UPDATE",
  MASTER_STATUS_PERKAWINAN_DELETE: "MASTER.STATUS_PERKAWINAN.DELETE",
  MASTER_STATUS_PERKAWINAN_RESTORE: "MASTER.STATUS_PERKAWINAN.RESTORE",

  // TEMPAT LAHIR
  MASTER_TEMPAT_LAHIR_VIEW: "MASTER.TEMPAT_LAHIR.VIEW",
  MASTER_TEMPAT_LAHIR_CREATE: "MASTER.TEMPAT_LAHIR.CREATE",
  MASTER_TEMPAT_LAHIR_UPDATE: "MASTER.TEMPAT_LAHIR.UPDATE",
  MASTER_TEMPAT_LAHIR_DELETE: "MASTER.TEMPAT_LAHIR.DELETE",
  MASTER_TEMPAT_LAHIR_RESTORE: "MASTER.TEMPAT_LAHIR.RESTORE",

  // UNOR
  MASTER_UNOR_VIEW: "MASTER.UNOR.VIEW",
  MASTER_UNOR_CREATE: "MASTER.UNOR.CREATE",
  MASTER_UNOR_UPDATE: "MASTER.UNOR.UPDATE",
  MASTER_UNOR_DELETE: "MASTER.UNOR.DELETE",
  MASTER_UNOR_RESTORE: "MASTER.UNOR.RESTORE",
 
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]